export const ADD_DRIVER = 'ADD_DRIVER'
export const REMOVE_DRIVER = 'REMOVE_DRIVER'
export const FILTER = 'FILTER'
export const ORDER = 'ORDER'
export const GET_DRIVERS = 'GET_DRIVERS'
export const GET_DETAIL = 'GET_DETAIL'